### ISSUE TITLE
flagged this file as malicious

### ISSUE THREAD

**Issue by kopitulin** [Henry00IS/HRequest#1]
[https://www.virustotal.com/gui/file/e4337a72d86e3f8d63b41a2604fab97729c78ad17d5593f6ac1a23f6c2654a75](url)

Security vendors' analysis

Bkav Pro
W32.AIDetectMalware
Cynet
Malicious (score: 100)
Elastic
Malicious (moderate Confidence)
MaxSecure
Trojan.Malware.300983.susgen
SecureAge
Malicious
Acronis (Static ML)
Undetected

**Comment by Henry00IS** [comment]
It's a false positive because I use PureBasic. Known problem:
https://www.purebasic.fr/english/viewtopic.php?t=78612
https://www.purebasic.fr/english/viewtopic.php?t=77459
https://www.purebasic.fr/english/viewtopic.php?t=72466
https://www.purebasic.fr/english/viewtopic.php?t=76051
https://www.purebasic.fr/english/viewtopic.php?t=69872
https://www.purebasic.fr/english/viewtopic.php?f=7&t=69166
http://forums.purebasic.com/english/viewtopic.php?t=75600
https://www.purebasic.fr/english/viewtopic.php?t=77433
https://www.purebasic.fr/english/viewtopic.php?t=61372
... and so on.

Just open the project in PureBasic and compile it yourself if you don't trust it. People wrote so much malware using the PureBasic standard library functions that every compiled executable gets flagged.

**Comment by Henry00IS** [comment]
But thank you for trying to keep everyone safe regardless. 👍
